### ISSUE TITLE
Examples/tutorial would be very useful

### ISSUE THREAD

**Issue by ddofborg** [uqfoundation/klepto#107]
The project looks very promising. I do miss examples though. It would help a lot to start quickly.

**Comment by mmckerns** [comment]
This is a duplicate of #23.  I agree, and one is coming.  Existing resources are: https://github.com/uqfoundation/klepto/tree/master/klepto/tests, which have a lot of examples of usage included, and [this talk/tutorial I gave](https://github.com/mmckerns/tlkklp) on `klepto`.
