### ISSUE TITLE
_file_archive.__save__ silently fails if cwd is not on same file system type as filename

### ISSUE THREAD

**Issue by drorspei** [uqfoundation/klepto#49]
I've started using klepto for persistence and it is amazing. Thanks :)

In `_file_archive.__save__`, a temporary files is created, the cache is dumped into it, and then the temporary file is renamed to the filename I gave at initialization. At this last point a known issue of `os.renames` on unix arises: if the temporary file and the filename are on different hard disks with different file systems, this fails.

Code to reproduce:

```
os.chdir('/my/fat32/disk')
f = klepto.archives.file_archive('/my/ntfs/disk/memo.pkl', serialized=True, cached=False)
assert os.path.isfile('/my/ntfs/disk/memo.pkl')
```

One solution that I saw on stackoverflow [1] was to replace <code>os.renames</code> with <code>shutil.move</code>, and this works for me.

Another solution is to make the temporary file in the same directory as the end file:
`_filename = os.path.join(os.path.dirname(os.path.abspath(filename)), TEMP+hash(random(), 'md5'))`
which also works for me. I prefer this solution since if the save fails for some reason, it is clearer where the temporary file is.

[1] http://stackoverflow.com/questions/11578443/trigger-io-errno-18-cross-device-link

**Comment by mmckerns** [comment]
@drorspei: thanks for your comments, and for the nice solution(s) to the issue.  Sorry I did not get to this earlier.  I've adopted your latter solution in 617e70d849be1a2a6623018e8167741d27c6d496.
