### ISSUE TITLE
Opening HDF5 archive in external viewers

### ISSUE THREAD

**Issue by arunveeramany** [uqfoundation/klepto#63]
The following works very well.

        archive_2 = hdf_archive('solution2.hdf5', serialized=True)
        archive_2[0] = [{'id':0, 'name':1}]
        archive_2.dump()

        archive_2 = hdf_archive('solution2.hdf5', {}, serialized=True, cached=True)
        archive_2.load()
        print archive_2[0][0]

However, when I try opening this archive in a tool like
HDFView (https://support.hdfgroup.org/products/java/release/download.html)
Panoply (https://www.giss.nasa.gov/tools/panoply/download/)

I see strange characters like: �]q

Is it because data is stored in binary format or these tools supposed to show the actual data?

**Comment by mmckerns** [comment]
Do the odd characters look like this?
```
>>> import dill
>>> dill.dumps([{'name': 1, 'id': 0}])
'\x80\x02]q\x00}q\x01(U\x04nameq\x02K\x01U\x02idq\x03K\x00ua.'
>>> dill.dumps(0)
'\x80\x02K\x00.'
```
Because you are using `serialized=True`, which means that the objects will be pickled before storing them in the HDF file.

**Comment by mmckerns** [comment]
`klepto` lets you pick an encoder, and there are several variants of serializing encoder.  But that is most certainly what you are seeing -- serialized python objects in the HDF5 file.

**Comment by arunveeramany** [comment]
Setting serialized=False results in:

TypeError: Object dtype dtype('O') has no native HDF5 equivalent


Here's h5dump solution2.hdf5 with serialized=True

HDF5 "solution2.hdf5" {
GROUP "/" {
   DATASET "I0
." {
      DATATYPE  H5T_STRING {
         STRSIZE 30;
         STRPAD H5T_STR_NULLPAD;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): "\37777777600\002]q\000}q\001(U\002idq\002K\000U\004nameq\003K\001ua.            "
      }
   }
}
}

So, what encoding should I set to ensure created HDF5 file can be opened in other viewers or from other languages?

**Comment by mmckerns** [comment]
you can try `string` or `json` -- `json` is probably best and can handle `lists` and `dicts`

**Comment by arunveeramany** [comment]
I can try json. Is this feature part of klepto? where do I set this option?

**Comment by mmckerns** [comment]
```
  class hdfdir_archive(dict):
      """dictionary-style interface to a folder of hdf5 files"""
      def __init__(self, dirname=None, serialized=True, **kwds):
          """initialize a hdf5 file with a synchronized dictionary interface

      Inputs:
          dirname: name of the root archive directory [default: memo]
          serialized: if True, pickle hdf entries; otherwise save python objects
          permissions: octal representing read/write permissions [default: 0o775]
          protocol: pickling protocol [default: None (use the default protocol)]
          meta: if True, store as file root metadata; otherwise store in datasets
          """
```
Looking at`klepto`, I added the ability to select the pickle protocol for the object that is stored... but don't allow selecting encoding as an option.  In a `klepto.cache`, you can pick the encoding -- but it's for the keys, primarily.  So, I think you might have to do what I suggested above, and do the `json.dumps` before passing to the archive. 

Maybe this is a worthwhile feature request -- to use `json` for serialization in the archive.

**Comment by arunveeramany** [comment]
Doing so (replacing dill), I am able to see contents in HDFViewer

        archive_2['b'] = [[0,1,2,3],[4,5,6,7]]
        archive_2.dump()

How do I set the column names? 

Does HDF5 support strings as well? I get TypeError with this:        
archive_2['b'] = [[0,1,2,3,'A'],[4,5,6,7,'B']]


![untitled](https://user-images.githubusercontent.com/26749419/41690678-82904a3e-74ab-11e8-8987-e0318119ea2f.png)

**Comment by mmckerns** [comment]
So you edited the source code yourself, and it works...?  That's good to know.  I will enable use of `json` when I have time to do that.

HDF5 does support strings... anything that is using `serialized=True` is being stored as a string, so I'm not sure why you are getting an error with `[[0,1,2,3,'A'],[4,5,6,7,'B']]`. Again, post the traceback, as that helps diagnose it.

You'd like to set the column names from the archive, or from `h5py`?

**Comment by arunveeramany** [comment]
Yes, replaced dill. to json. in hdf_archive and it worked.

setting serialized=True inserted just one column with entire json string in it rather than separating them into columns. screenshot is attached.

It would be great if I can set the column names from klepto itself. I am using dill version of klepto, but also need the json version of klepto to support clients who can generate hdf5 file (including myself) from any language of their choice. I should be able to read their HDF5 file using klepto.

![untitled](https://user-images.githubusercontent.com/26749419/41693468-450dd9a6-74ba-11e8-915a-03c8ad966502.png)

**Comment by mmckerns** [comment]
@arunveeramany: here's what I propose.  I'm releasing a new version of `klepto` in a few minutes, and should have another new release out by August.  I'll definitely add the ability to use an alternate serializer as proposed in #64 before the latter release.  If you open a new issue describing what you want in terms of metadata in the HDF5 file, then I'll also evaluate and try to get into the August release.  Sound good?  You might want to check out the `to_frame` method that dumps an archive to a `pandas.DataFrame`.  If that seems to add the metadata you are looking for, then that makes it easy for me to port it to the HDF5 archives.  Also, if we are done here, then close this issue -- but do please open a new issue with what you would like to see with metadata in the HDF5 file.
