### ISSUE TITLE
raspian corrupts file contents

### ISSUE THREAD

**Issue by rob9321** [uqfoundation/klepto#68]
In Raspian, using klepto to store something will always print in the stored file €}q. The same code in Windows works properly. Even rsync the Windows DBfile to the Linux machine, or copy-paste trough VNC will have the same result. Am i doing something wrong?

**Comment by mmckerns** [comment]
@rob9321: can you be a bit more explicit?  Essentially, post some minimal code that reproduces the behavior you are seeing?  I can't answer your question as is.  I've not seen filename errors on Linux.  I test on linux, mac, and windows... but not with raspian.  Which python are you using?  Again, please post minimal code showing the issue.

**Comment by rob9321** [comment]
Okey, code is like this:
```
from klepto.archives import file_archive
pk = file_archive(pathtofile)

object = myClass(something) 
pk[object.getID()] = object  #obv object has an attribute ID and a method getID()
pk.dump()


```
In Windows it work as it should, in raspian klepto will always print in pathtofile the following characters:
https://imgur.com/a/8hsbdrS

Even run the program  and print in the file (correctly) on Windows and transfer it on Raspian will lead to the same result

Hope im being helpful,
Thank you

**Comment by mmckerns** [comment]
@rob9321: that code works for me on linux, mac, and windows for different versions of python.  I don't have raspian to test on.

I did:
```
>>> from klepto.archives import file_archive
>>> pk = file_archive('testme')
>>> class Foo(object):
...   def id(self):
...     return id(self)
...
>>> f = Foo()
>>> pk[f.id()] = f
>>> pk.dump()
```
and that seems to work.

**Comment by mmckerns** [comment]
you using python 3?  which version?

**Comment by mmckerns** [comment]
If you just do: `pk = file_archive('testme')`, then type `pk` what do you see?  what do the file contents look like?

**Comment by rob9321** [comment]
Im using Python 3.5.3.

Running it as you said printed on terminal

`file_archive('testme',{}, cached = True) 
`

**Comment by mmckerns** [comment]
Hmmm... I'm not sure what to do here, as I can't test it right now.  Would you be wiling to try to walk through the source code step by step where the string gets mangled from `"testme"` by walking through the steps the underlying source code takes?  In the meantime I'll see if I can find Rasbian and reproduce your environment.

**Comment by mmckerns** [comment]
Can you provide the output you see when you run this code?

```
>>> import klepto as kl
>>> ar = kl._archives.file_archive('testme')
>>> ar.__state__
{'serialized': True, 'protocol': None, 'id': 'testme'}
>>> ar.__reduce__()
(<class 'klepto._archives.file_archive'>, ('testme', True), {'__state__': {'serialized': True, 'protocol': None, 'id': 'testme'}})
>>> ar.name
'testme'
>>> ar.state
{'serialized': True, 'protocol': None, 'id': 'testme'}
>>> ar.archive
file_archive('testme', {}, cached=False)
>>> 
```

And if you see the output as above, can you repeat with `cached=True`?

**Comment by rob9321** [comment]
The output you requested is:

```
>>> import klepto as kl
>>> ar = kl._archives.file_archive('testme')
>>> ar.__state__
{'protocol': None, 'serialized': True, 'id': 'testme'}

>>> ar.__reduce__()
(<class 'klepto._archives.file_archive'>, ('testme', True), {'__state__': {'protocol': None, 'serialized': True, 'id': 'testme'}})
>>> ar.name
'testme'
>>> ar.state
{'id': 'testme', 'serialized': True, 'protocol': None}
>>> ar.archive
file_archive('testme', {}, cached=False)

```
exactly as yours. In the testme file the output is the usual four strange characters.

I dont really get it how i can repeat with `cached = True`

And if this is gonna put on you too much effort, dont worry ill find another way to store things. And very very thank you for your support!

**Comment by mmckerns** [comment]
No worries... if you don't mind the (slow) back and forth, then I don't mind, especially if it helps you workaround it, or we find a bug.   Sorry I don't have a PI I can test on.

I do see I misunderstood your original question slightly, however.  Can you try:
```
>>> from klepto.archives import file_archive      
>>> file_archive('pickle2', serialized=True, protocol=2)
file_archive('pickle2', {}, cached=True)
>>> file_archive('pickle0', serialized=True, protocol=0)
file_archive('pickle0', {}, cached=True)
>>> file_archive('json0', serialized=True, protocol='json')
file_archive('json0', {}, cached=True)
>>> file_archive('object0', serialized=False)
file_archive('object0.py', {}, cached=True)
>>> 
```

and tell me what you see in the file?

I think what you are seeing is some encoded strings.  `klepto` can encode both the stored keys and the stored values.   See `klepto.keymaps`.

**Comment by mmckerns** [comment]
closing this as stale.  Please reopen if there's more to add here.
