### ISSUE TITLE
The argument of caches `purge` should be set to False by default

### ISSUE THREAD

**Issue by iven00000000** [uqfoundation/klepto#77]
If `purge` is set to `True`, when the number of entries reaches the limit, all data will be dumped and the states will be cleared, so all kind of caches (e.g. `lru_cache`, `lfu_cache`, ...) will act in the same behaviour.

**Comment by mmckerns** [comment]
By default, the caches all act differently (governed by their namesake behavior).  However, when an archive is attached, then the behavior is to `dump` to the archive when the maximum size is reached -- that is, unless `purge == True`.  This was the intended behavior.  By toggling purge, you can essentially toggle the archiving behavior.  It sounds like you are arguing that attaching an archive shouldn't change the default behavior, until `purge` is set to `True`.   Hmm... maybe that's a slightly better choice.

**Comment by iven00000000** [comment]
Thank you for following up. Yes, that attaching an archive shouldn't change the default behavior is what I argued. The behaviour when `purge` is set to `False` is more intuitive to the users(developers who use this project).
