### ISSUE TITLE
Archive thread safety

### ISSUE THREAD

**Issue by AndreasAlbert** [uqfoundation/klepto#78]
(Related to #41)

Hi,

is there any documentation on which archives are thread safe? Specifically, I'd like to have multiple processes write to the same serialized `dir_archive`. I'd assume this works fine if I can guarantee that no two processes ever touch the same key, but I am not certain.

Thanks

**Comment by mmckerns** [comment]
> is there any documentation on which archives are thread safe?

Documentation... no, but there should be.
