### ISSUE TITLE
Automatically dumping and loading the cache for each change?

### ISSUE THREAD

**Issue by petebachant** [uqfoundation/klepto#81]
Let me know if this is out of scope, but I'd like the cache to persist on disk (probably as HDF5 or a directory of HDF5 files) to be used in a different session, e.g., after a reboot. Is it possible to tell the cache to automatically dump new, or "missed" entries to the archive and automatically load upon instantiation?

Bonus question: Is it possible to find the age of an entry or when it was dumped?

**Comment by mmckerns** [comment]
I'm not sure what you are asking for, specifically. `klepto` can use a HDF5 backend, and if you want the files to be automatically sync'd, then use `cached=False` when creating the `klepto.archive`.  That setting will make sure the archive does not use a in-memory cache, but instead interacts directly with the selected archive backend.  If you are using a cached archive, then if you want the backend sync'd, you can either `dump`, `load`, `sync`, or similar.

With regard to the age of the entry, or when it was dumped... no.  Not really.  There are plans to add a cache expiry algorithm that expires entries after a selected time.

**Comment by petebachant** [comment]
I meant something that would do both use memory caching, and if an object is not in memory but on disk, load from there. I suppose this is a hybrid of the two. Thanks for letting me know it's not implemented in this package!

**Comment by mmckerns** [comment]
If the archive has `cached=True`, and the archive uses, say, a HDF backend... it will interact with the memory cache first when it does a lookup... but  if the key is not found in memory, it may try to load from the archive.  So... I guess I'm still not sure what you are asking...  as it seems like what you want is a feature of `klepto` already.

**Comment by mmckerns** [comment]
```
>>> import klepto as kl
>>> c = kl.inf_cache(cache=kl.archives.hdf_archive('foo.h5', cached=True))
>>> @c
... def foo(x): 
...   print('called')
...   return x*x*x
... 
>>> foo(1)
called
1
>>> foo(2)
called
8
>>> foo(3)
called
27
>>> foo(2)
8
```

Now we dump all of the entries to the backend, and clear everything from memory.
```
>>> foo.dump()
>>> foo.clear()
>>> foo.__cache__()
hdf_archive('foo.h5', {}, cached=True)
>>> foo.__cache__().__archive__
hdf_archive('foo.h5', {-8145078762942369576: 8, -8145078762943452101: 27, -8145078762941287051: 1}, cached=False)
```

You can still see that keys that are in the archive, but not in the memory cache are still looked up (i.e. not called).
```
>>> foo(4)
called
64
>>> foo(1)
1
>>> foo.__cache__()
hdf_archive('foo.h5', {-8145078762941287051: 1, -8145078762935874426: 64}, cached=True)
>>> foo.__cache__().__archive__
hdf_archive('foo.h5', {-8145078762942369576: 8, -8145078762943452101: 27, -8145078762941287051: 1}, cached=False)
>>> foo.key(1)
-8145078762941287051
```

**Comment by petebachant** [comment]
I guess I was hoping `dump` would be called every time a new object was cached, and also that `dump` would happen on a per-object basis, rather than the entire cache at once.

A usage example could be acquiring a bunch of data from a database and trying to process it, where the processing crashes or something. If the user didn't call `dump` before processing the data, they'd need to go through that time consuming step of downloading the data again.

**Comment by mmckerns** [comment]
`dump`, `load`, etc, doesn't need to be on the entire cache.  If you pass specific keys to `dump`, etc, then it will only work on the objects passed.

If you have particular use cases in mind... maybe generate some pseudo code here, and I can better sort out what you want.  Or maybe, is it that the documentation is lacking?

**Comment by petebachant** [comment]
I ended up rolling my own solution based on cachetools LRU cache, which added the ability to always dump cached DataFrames (the only type of objects that get cached) to HDF5 as soon as they were set, and also to clear expired items based on age.

Here's a sample of what happens when

```python
    def __getitem__(self, key):
        if key not in self.keys() and str(key) in self.hdf_keys:
            value = pd.read_hdf(self.fpath, str(key))
            super().__setitem__(key, value)
        return super().__getitem__(key)

    def __setitem__(self, key, value):
        self.clear_expired()
        # First trim HDF5 file if we would exceed max size
        # We will remove the oldest entries first, which is not LRU, as the
        # cache in memory is
        while self.hdf_size + self.getsizeof(value) > self.maxsize:
            oldest = self.stored.idxmax()
            with h5py.File(self.fpath, "a") as f:
                _ = f.pop(oldest)
            _ = self.stored.pop(oldest)
            self.write_stored()
        self.store(key, value)
        super().__setitem__(key, value)
```
