### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by nershman** [uqfoundation/klepto#85]
Hello,
I am picking up a project from someone else which uses klepto, and I am pretty new to python. The klepto archive is a file_archive with tuples of string and integer as keys ({"string"},1010). Because of the double quotes in the folder names, it's not possible to open on my Windows machine. I'm wondering what's a simple workaround in order to make it compatible on both windows and linux. I was going to re-archive it as a file_archive, but I can't figure out how to convert the klepto cache into a dict so I can do that. I also read another issue you opened which mentioned changing the keymap to use hashmaps, would this be an option?

Thanks for your help. I'm pretty new to this so sorry if this is trivial.

**Comment by nershman** [comment]
Here's the code I found that does the trick. I don't fully understand the structure of the archive objects, but there is a method _to_dict_() which you must use to get a normal dict again. And to send the dict back to a klepto archive you have to iterate through the keys and add them to the klepto archive, just like you would a dict. Then dump() will save it all.


```
fl_arch = klepto.archives.dir_archive('YOUR_FILE_ARCHIVE_DIR', 
                                                     cached=True, 
                                                     serialized=True) #fl_arch is type cache.
fl_arch.load() #does nothing, but is required for accessing cache according to _archive.py

temp = fl_arch.__dict__ #type dict containing archive
tempdirarchive = temp['__archive__'] #type dir_archive
tempdict = tempdirarchive.__asdict__() #the original dict

#create new archive object
newk = klepto.archives.file_archive('YOUR_DIR/memo.pkl', 
                                                     cached=True, 
                                                     serialized=True)

#loop to add the dict keys & data to new klepto archive
for i in tempdict.keys():
    newk[i] = tempdict[i]

#save to disk

newk.dump()
```
I found comments in _archives.py to be most helpful in learning how this works. Cheers!

**Comment by IvanaGyro** [comment]
Filenames with double quotes are still the problem on Windows, right? Maybe the default hash function should be redesigned for the compatibility on Windows.

**Comment by nershman** [comment]
Yes, they are. There is another issue here which is similar: https://github.com/uqfoundation/klepto/issues/11

**Comment by mmckerns** [comment]
Hey @nershman thanks for the post.  Can you be a little more explicit here on what your issue was (i.e. in code), and also give any recommendations on what you'd like to see?

**Comment by nershman** [comment]
I'm not really sure what code to give you for the issue, sorry. I copied the folder for a dir_archive to a windows machine, and the files had doublequotes in them which are not accessible on a windows machine. So in python it will throw FileNotFound errors when trying to load the dir_archive.

I have a couple ideas that might be helpful for users of this tool:
1) throw a warning when using dir_archive with characters which may cause issues on other machines
2) I believe I read something about an option to name folders in dir_archive with hash keys instead of the object names, but I couldn't find information on how to do this. It would also be a good workaround.
3) Maybe folders could replace non-compatible characters with underscores, but this might cause more complications than it's worth.
