### ISSUE TITLE
retrieve data from klepto

### ISSUE THREAD

**Issue by garretvo19** [uqfoundation/klepto#92]
Hi,

 Thank you for klepto. I really like the package. This is my first time using it. I just have a quick question. How would you retrive data after archive it? I have a large dictionary and I use klepto to dump the data with dir_archive. I am just wondering how I can retrieve a particular value from the key of the dictionary. Thank you

**Comment by garretvo19** [comment]
I have a solution.

**Comment by mmckerns** [comment]
@garretvo19: In short, when you have a handle to an archive (created with `a = dir_archive`), then you can retrieve the value for `foo` by `a['foo']`.  Although it depends on whether or not you have `cached=True`, so if it's cached, you may have to use `load` first.
